services:
  - type: web
    name: sdk-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sdk_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
